name              'ark'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Provides a custom resource for installing runtime artifacts in a predictable fashion'
version           '6.0.33'
source_url        'https://github.com/sous-chefs/ark'
issues_url        'https://github.com/sous-chefs/ark/issues'
chef_version      '>= 15.3'

supports 'almalinux', '>= 8.0'
supports 'amazon', '>= 2023.0'
supports 'centos_stream', '>= 9.0'
supports 'debian', '>= 12.0'
supports 'fedora'
supports 'freebsd', '>= 13.0'
supports 'mac_os_x'
supports 'opensuseleap', '>= 15.0'
supports 'oracle', '>= 8.0'
supports 'redhat', '>= 8.0'
supports 'rocky', '>= 8.0'
supports 'smartos'
supports 'suse'
supports 'ubuntu', '>= 22.04'
supports 'windows'

depends 'seven_zip', '>= 3.1' # for windows os
